---
# SPDX-FileCopyrightText: 2025 Vasco Guita <vasco@guita.org>
#
# SPDX-License-Identifier: MIT

name: Build LaTeX document
on: [push, workflow_dispatch]
permissions:
  contents: read
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - uses: actions/upload-artifact@v4
        with:
          path: cv.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
