name: Build LaTeX document
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          post_compile: "mv main.pdf cv.pdf"
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: cv.pdf
