---
name: Lint LaTeX document
on: [push, workflow_dispatch]
permissions:
  contents: read
jobs:
  lint_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Run ChkTeX
        uses: j2kun/chktex-action@v2
        with:
          lint-all: true
