---
# SPDX-FileCopyrightText: 2025 Vasco Guita <vasco@guita.org>
#
# SPDX-License-Identifier: MIT

name: Lint
on: [push, workflow_dispatch]
permissions:
  contents: read
jobs:
  lint-latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Lint LaTeX
        run: make lint-latex
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install markdownlint-cli2
        run: npm install markdownlint-cli2 --global
      - name: Lint Markdown
        run: make lint-md
  lint-make:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install checkmake
        run: |
          go install github.com/checkmake/checkmake/cmd/checkmake@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Lint Makefile
        run: make lint-make
  lint-license:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install reuse
        run: pip install reuse
      - name: Lint License
        run: make lint-license
